### PR TITLE
Support for slither action & hardhat unit test action

### PR DESCRIPTION
**Pull request by niket-yende**
Added support for these github actions for checking below:

- Highlight slither recommendations for smart contract changes.
- Run the hardhat unit test cases.

Note: As a pre-requisite, the env variables need to be added to the repository secrets.
env:
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

The output of slither action could be viewed under the security->code scanning section.

### CODE REVIEW

**Comment by niket-yende** [comment]
@PatrickAlphaC Please review the PR at your earliest convenience.

**Comment by PatrickAlphaC** [comment]
why do you need the secrets? You shouldn't need these. This is not good practice to have a private key in the CI/CD pipeline.

**Comment by niket-yende** [comment]
Hi @PatrickAlphaC , thanks for letting me know. I have set the default env values inside the hardhat config, instead of setting them from the repo secrets section.

Note: The values used in the secret were also dummy values.

Please review these changes at your earliest convenience. Thanks :)

**Comment by PatrickAlphaC** [comment]
Much better :) 

Ty!!

**Pull request merged**
