### PR TITLE
Updated dev dependencies and solidity version

### PR DESCRIPTION
**Pull request by niket-yende**
This PR includes below changes:

1. Solidity updated to 0.8.21 version.
2. Updated important dev dependencies:

- @nomiclabs/hardhat-ethers
- @nomiclabs/hardhat-etherscan
- @nomiclabs/hardhat-waffle
- @openzeppelin/contracts
- @typechain/ethers-v6 (Upgraded to v6)
- @typechain/hardhat
- @types/node
- ethereum-waffle
- ethers
- hardhat
- hardhat-deploy
- hardhat-gas-reporter
- ts-node
- typechain

Note: These changes have been tested against the usage example commands & the test case.

### CODE REVIEW

**Comment by niket-yende** [comment]
@PatrickAlphaC, kindly take some time at your earliest convenience to review this pull request. Your feedback and insights would be greatly appreciated.

**Comment by PatrickAlphaC** [comment]
Can we use 0.8.18 of solidity? Slither still recommends that version.

**Comment by niket-yende** [comment]
> Can we use 0.8.18 of solidity? Slither still recommends that version.

Updated the solidity version to 0.8.18 as per the suggestion.

**Comment by niket-yende** [comment]
Hi @PatrickAlphaC, are there any further suggestions for this PR?

**Comment by niket-yende** [comment]
Hey @PatrickAlphaC, I just wanted to check if there are any further suggestions to improve this PR. Your feedback is greatly appreciated.

**Comment by PatrickAlphaC** [comment]
Merged!

**Pull request merged**
